//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignatureType {
    
    private SignedInfoType signedInfoField;
    
    private SignatureValueType signatureValueField;
    
    private KeyInfoType keyInfoField;
    
    private ObjectType[] objectField;
    
    private string idField;
    
    /// <remarks/>
    public SignedInfoType SignedInfo {
        get {
            return this.signedInfoField;
        }
        set {
            this.signedInfoField = value;
        }
    }
    
    /// <remarks/>
    public SignatureValueType SignatureValue {
        get {
            return this.signatureValueField;
        }
        set {
            this.signatureValueField = value;
        }
    }
    
    /// <remarks/>
    public KeyInfoType KeyInfo {
        get {
            return this.keyInfoField;
        }
        set {
            this.keyInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Object")]
    public ObjectType[] Object {
        get {
            return this.objectField;
        }
        set {
            this.objectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignedInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignedInfoType {
    
    private CanonicalizationMethodType canonicalizationMethodField;
    
    private SignatureMethodType signatureMethodField;
    
    private ReferenceType[] referenceField;
    
    private string idField;
    
    /// <remarks/>
    public CanonicalizationMethodType CanonicalizationMethod {
        get {
            return this.canonicalizationMethodField;
        }
        set {
            this.canonicalizationMethodField = value;
        }
    }
    
    /// <remarks/>
    public SignatureMethodType SignatureMethod {
        get {
            return this.signatureMethodField;
        }
        set {
            this.signatureMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public ReferenceType[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("CanonicalizationMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class CanonicalizationMethodType {
    
    private System.Xml.XmlNode[] anyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class X509IssuerSerialType {
    
    private string x509IssuerNameField;
    
    private string x509SerialNumberField;
    
    /// <remarks/>
    public string X509IssuerName {
        get {
            return this.x509IssuerNameField;
        }
        set {
            this.x509IssuerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string X509SerialNumber {
        get {
            return this.x509SerialNumberField;
        }
        set {
            this.x509SerialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignatureMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignatureMethodType {
    
    private string hMACOutputLengthField;
    
    private System.Xml.XmlNode[] anyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string HMACOutputLength {
        get {
            return this.hMACOutputLengthField;
        }
        set {
            this.hMACOutputLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Reference", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class ReferenceType {
    
    private TransformType[] transformsField;
    
    private DigestMethodType digestMethodField;
    
    private byte[] digestValueField;
    
    private string idField;
    
    private string uRIField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
    public TransformType[] Transforms {
        get {
            return this.transformsField;
        }
        set {
            this.transformsField = value;
        }
    }
    
    /// <remarks/>
    public DigestMethodType DigestMethod {
        get {
            return this.digestMethodField;
        }
        set {
            this.digestMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] DigestValue {
        get {
            return this.digestValueField;
        }
        set {
            this.digestValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Transform", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class TransformType {
    
    private object[] itemsField;
    
    private string[] textField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("DigestMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class DigestMethodType {
    
    private System.Xml.XmlNode[] anyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignatureValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignatureValueType {
    
    private string idField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("KeyInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class KeyInfoType {
    
    private object[] itemsField;
    
    private ItemsChoiceType2[] itemsElementNameField;
    
    private string[] textField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType))]
    [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType))]
    [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType))]
    [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType))]
    [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType2[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("KeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class KeyValueType {
    
    private object itemField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType))]
    [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class DSAKeyValueType {
    
    private byte[] pField;
    
    private byte[] qField;
    
    private byte[] gField;
    
    private byte[] yField;
    
    private byte[] jField;
    
    private byte[] seedField;
    
    private byte[] pgenCounterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] P {
        get {
            return this.pField;
        }
        set {
            this.pField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Q {
        get {
            return this.qField;
        }
        set {
            this.qField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] G {
        get {
            return this.gField;
        }
        set {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] J {
        get {
            return this.jField;
        }
        set {
            this.jField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Seed {
        get {
            return this.seedField;
        }
        set {
            this.seedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] PgenCounter {
        get {
            return this.pgenCounterField;
        }
        set {
            this.pgenCounterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("RSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class RSAKeyValueType {
    
    private byte[] modulusField;
    
    private byte[] exponentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Modulus {
        get {
            return this.modulusField;
        }
        set {
            this.modulusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Exponent {
        get {
            return this.exponentField;
        }
        set {
            this.exponentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("PGPData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class PGPDataType {
    
    private object[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    PGPKeyID,
    
    /// <remarks/>
    PGPKeyPacket,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("RetrievalMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class RetrievalMethodType {
    
    private TransformType[] transformsField;
    
    private string uRIField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
    public TransformType[] Transforms {
        get {
            return this.transformsField;
        }
        set {
            this.transformsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SPKIData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SPKIDataType {
    
    private byte[][] sPKISexpField;
    
    private System.Xml.XmlElement anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType="base64Binary")]
    public byte[][] SPKISexp {
        get {
            return this.sPKISexpField;
        }
        set {
            this.sPKISexpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("X509Data", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class X509DataType {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType))]
    [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    X509CRL,
    
    /// <remarks/>
    X509Certificate,
    
    /// <remarks/>
    X509IssuerSerial,
    
    /// <remarks/>
    X509SKI,
    
    /// <remarks/>
    X509SubjectName,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
public enum ItemsChoiceType2 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    KeyName,
    
    /// <remarks/>
    KeyValue,
    
    /// <remarks/>
    MgmtData,
    
    /// <remarks/>
    PGPData,
    
    /// <remarks/>
    RetrievalMethod,
    
    /// <remarks/>
    SPKIData,
    
    /// <remarks/>
    X509Data,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Object", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class ObjectType {
    
    private System.Xml.XmlNode[] anyField;
    
    private string idField;
    
    private string mimeTypeField;
    
    private string encodingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MimeType {
        get {
            return this.mimeTypeField;
        }
        set {
            this.mimeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Transforms", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class TransformsType {
    
    private TransformType[] transformField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Transform")]
    public TransformType[] Transform {
        get {
            return this.transformField;
        }
        set {
            this.transformField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Manifest", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class ManifestType {
    
    private ReferenceType[] referenceField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public ReferenceType[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignatureProperties", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignaturePropertiesType {
    
    private SignaturePropertyType[] signaturePropertyField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SignatureProperty")]
    public SignaturePropertyType[] SignatureProperty {
        get {
            return this.signaturePropertyField;
        }
        set {
            this.signaturePropertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("SignatureProperty", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignaturePropertyType {
    
    private System.Xml.XmlElement[] itemsField;
    
    private string[] textField;
    
    private string targetField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
[System.Xml.Serialization.XmlRootAttribute("Diploma", Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", IsNullable=false)]
public partial class TDiploma {
    
    private TInfDiploma infDiplomaField;
    
    private SignatureType signatureField;
    
    /// <remarks/>
    public TInfDiploma infDiploma {
        get {
            return this.infDiplomaField;
        }
        set {
            this.infDiplomaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TInfDiploma {
    
    private object itemField;
    
    private object item1Field;
    
    private TVersao versaoField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DadosDiploma", typeof(TDadosDiploma))]
    [System.Xml.Serialization.XmlElementAttribute("DadosDiplomaNSF", typeof(TDadosDiplomaNSF))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DadosRegistro", typeof(TDadosRegistro))]
    [System.Xml.Serialization.XmlElementAttribute("DadosRegistroNSF", typeof(TDadosRegistroNSF))]
    public object Item1 {
        get {
            return this.item1Field;
        }
        set {
            this.item1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TVersao versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosDiploma {
    
    private TDadosDiplomado diplomadoField;
    
    private System.DateTime dataConclusaoField;
    
    private bool dataConclusaoFieldSpecified;
    
    private TDadosCurso dadosCursoField;
    
    private TDadosIesEmissora iesEmissoraField;
    
    private SignatureType[] signatureField;
    
    private string idField;
    
    /// <remarks/>
    public TDadosDiplomado Diplomado {
        get {
            return this.diplomadoField;
        }
        set {
            this.diplomadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataConclusao {
        get {
            return this.dataConclusaoField;
        }
        set {
            this.dataConclusaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataConclusaoSpecified {
        get {
            return this.dataConclusaoFieldSpecified;
        }
        set {
            this.dataConclusaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TDadosCurso DadosCurso {
        get {
            return this.dadosCursoField;
        }
        set {
            this.dadosCursoField = value;
        }
    }
    
    /// <remarks/>
    public TDadosIesEmissora IesEmissora {
        get {
            return this.iesEmissoraField;
        }
        set {
            this.iesEmissoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType[] Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosDiplomado {
    
    private string idField;
    
    private string nomeField;
    
    private string nomeSocialField;
    
    private TSexo sexoField;
    
    private string nacionalidadeField;
    
    private TNaturalidade naturalidadeField;
    
    private string cPFField;
    
    private object itemField;
    
    private System.DateTime dataNascimentoField;
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    public string NomeSocial {
        get {
            return this.nomeSocialField;
        }
        set {
            this.nomeSocialField = value;
        }
    }
    
    /// <remarks/>
    public TSexo Sexo {
        get {
            return this.sexoField;
        }
        set {
            this.sexoField = value;
        }
    }
    
    /// <remarks/>
    public string Nacionalidade {
        get {
            return this.nacionalidadeField;
        }
        set {
            this.nacionalidadeField = value;
        }
    }
    
    /// <remarks/>
    public TNaturalidade Naturalidade {
        get {
            return this.naturalidadeField;
        }
        set {
            this.naturalidadeField = value;
        }
    }
    
    /// <remarks/>
    public string CPF {
        get {
            return this.cPFField;
        }
        set {
            this.cPFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OutroDocumentoIdentificacao", typeof(TOutroDocumentoIdentificacao))]
    [System.Xml.Serialization.XmlElementAttribute("RG", typeof(TRg))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataNascimento {
        get {
            return this.dataNascimentoField;
        }
        set {
            this.dataNascimentoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public enum TSexo {
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    M,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TNaturalidade {
    
    private object[] itemsField;
    
    private ItemsChoiceType3[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CodigoMunicipio", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NomeMunicipio", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NomeMunicipioEstrangeiro", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("UF", typeof(TUf))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType3[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public enum TUf {
    
    /// <remarks/>
    AC,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    BA,
    
    /// <remarks/>
    CE,
    
    /// <remarks/>
    DF,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    GO,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PB,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    PI,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    RJ,
    
    /// <remarks/>
    RN,
    
    /// <remarks/>
    RO,
    
    /// <remarks/>
    RR,
    
    /// <remarks/>
    RS,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    SP,
    
    /// <remarks/>
    TO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", IncludeInSchema=false)]
public enum ItemsChoiceType3 {
    
    /// <remarks/>
    CodigoMunicipio,
    
    /// <remarks/>
    NomeMunicipio,
    
    /// <remarks/>
    NomeMunicipioEstrangeiro,
    
    /// <remarks/>
    UF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TOutroDocumentoIdentificacao {
    
    private string tipoDocumentoField;
    
    private string identificadorField;
    
    /// <remarks/>
    public string TipoDocumento {
        get {
            return this.tipoDocumentoField;
        }
        set {
            this.tipoDocumentoField = value;
        }
    }
    
    /// <remarks/>
    public string Identificador {
        get {
            return this.identificadorField;
        }
        set {
            this.identificadorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TRg {
    
    private string numeroField;
    
    private string orgaoExpedidorField;
    
    private TUf ufField;
    
    /// <remarks/>
    public string Numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    public string OrgaoExpedidor {
        get {
            return this.orgaoExpedidorField;
        }
        set {
            this.orgaoExpedidorField = value;
        }
    }
    
    /// <remarks/>
    public TUf UF {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosCurso {
    
    private string nomeCursoField;
    
    private object itemField;
    
    private string nomeHabilitacaoField;
    
    private TModalidadeCurso modalidadeField;
    
    private TTituloConferido tituloConferidoField;
    
    private TGrauConferido grauConferidoField;
    
    private TEndereco enderecoCursoField;
    
    private TPolo poloField;
    
    private TAtoRegulatorioComOuSemEMEC autorizacaoField;
    
    private TAtoRegulatorioComOuSemEMEC reconhecimentoField;
    
    private TAtoRegulatorioComOuSemEMEC renovacaoReconhecimentoField;
    
    /// <remarks/>
    public string NomeCurso {
        get {
            return this.nomeCursoField;
        }
        set {
            this.nomeCursoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CodigoCursoEMEC", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("SemCodigoCursoEMEC", typeof(TInformacoesTramitacaoEMEC))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public string NomeHabilitacao {
        get {
            return this.nomeHabilitacaoField;
        }
        set {
            this.nomeHabilitacaoField = value;
        }
    }
    
    /// <remarks/>
    public TModalidadeCurso Modalidade {
        get {
            return this.modalidadeField;
        }
        set {
            this.modalidadeField = value;
        }
    }
    
    /// <remarks/>
    public TTituloConferido TituloConferido {
        get {
            return this.tituloConferidoField;
        }
        set {
            this.tituloConferidoField = value;
        }
    }
    
    /// <remarks/>
    public TGrauConferido GrauConferido {
        get {
            return this.grauConferidoField;
        }
        set {
            this.grauConferidoField = value;
        }
    }
    
    /// <remarks/>
    public TEndereco EnderecoCurso {
        get {
            return this.enderecoCursoField;
        }
        set {
            this.enderecoCursoField = value;
        }
    }
    
    /// <remarks/>
    public TPolo Polo {
        get {
            return this.poloField;
        }
        set {
            this.poloField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC Autorizacao {
        get {
            return this.autorizacaoField;
        }
        set {
            this.autorizacaoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC Reconhecimento {
        get {
            return this.reconhecimentoField;
        }
        set {
            this.reconhecimentoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC RenovacaoReconhecimento {
        get {
            return this.renovacaoReconhecimentoField;
        }
        set {
            this.renovacaoReconhecimentoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TInformacoesTramitacaoEMEC {
    
    private uint numeroProcessoField;
    
    private string tipoProcessoField;
    
    private System.DateTime dataCadastroField;
    
    private System.DateTime dataProtocoloField;
    
    /// <remarks/>
    public uint NumeroProcesso {
        get {
            return this.numeroProcessoField;
        }
        set {
            this.numeroProcessoField = value;
        }
    }
    
    /// <remarks/>
    public string TipoProcesso {
        get {
            return this.tipoProcessoField;
        }
        set {
            this.tipoProcessoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataCadastro {
        get {
            return this.dataCadastroField;
        }
        set {
            this.dataCadastroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataProtocolo {
        get {
            return this.dataProtocoloField;
        }
        set {
            this.dataProtocoloField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public enum TModalidadeCurso {
    
    /// <remarks/>
    Presencial,
    
    /// <remarks/>
    EAD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TTituloConferido {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OutroTitulo", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Titulo", typeof(TTitulo))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public enum TTitulo {
    
    /// <remarks/>
    Licenciado,
    
    /// <remarks/>
    Técnico,
    
    /// <remarks/>
    Bacharel,
    
    /// <remarks/>
    Médico,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public enum TGrauConferido {
    
    /// <remarks/>
    Tecnólogo,
    
    /// <remarks/>
    Bacharelado,
    
    /// <remarks/>
    Licenciatura,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Curso sequencial")]
    Cursosequencial,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TEndereco {
    
    private string logradouroField;
    
    private string numeroField;
    
    private string complementoField;
    
    private string bairroField;
    
    private string codigoMunicipioField;
    
    private string nomeMunicipioField;
    
    private TUf ufField;
    
    private string nomeMunicipioEstrangeiroField;
    
    private string cEPField;
    
    /// <remarks/>
    public string Logradouro {
        get {
            return this.logradouroField;
        }
        set {
            this.logradouroField = value;
        }
    }
    
    /// <remarks/>
    public string Numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    public string Complemento {
        get {
            return this.complementoField;
        }
        set {
            this.complementoField = value;
        }
    }
    
    /// <remarks/>
    public string Bairro {
        get {
            return this.bairroField;
        }
        set {
            this.bairroField = value;
        }
    }
    
    /// <remarks/>
    public string CodigoMunicipio {
        get {
            return this.codigoMunicipioField;
        }
        set {
            this.codigoMunicipioField = value;
        }
    }
    
    /// <remarks/>
    public string NomeMunicipio {
        get {
            return this.nomeMunicipioField;
        }
        set {
            this.nomeMunicipioField = value;
        }
    }
    
    /// <remarks/>
    public TUf UF {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
        }
    }
    
    /// <remarks/>
    public string NomeMunicipioEstrangeiro {
        get {
            return this.nomeMunicipioEstrangeiroField;
        }
        set {
            this.nomeMunicipioEstrangeiroField = value;
        }
    }
    
    /// <remarks/>
    public string CEP {
        get {
            return this.cEPField;
        }
        set {
            this.cEPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TPolo {
    
    private string nomeField;
    
    private TEndereco enderecoField;
    
    private object itemField;
    
    /// <remarks/>
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    public TEndereco Endereco {
        get {
            return this.enderecoField;
        }
        set {
            this.enderecoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CodigoEMEC", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("SemCodigoEMEC", typeof(TInformacoesTramitacaoEMEC))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TAtoRegulatorioComOuSemEMEC {
    
    private TTipoAtoComAtoProprio tipoField;
    
    private string numeroField;
    
    private System.DateTime dataField;
    
    private string veiculoPublicacaoField;
    
    private System.DateTime dataPublicacaoField;
    
    private bool dataPublicacaoFieldSpecified;
    
    private uint secaoPublicacaoField;
    
    private bool secaoPublicacaoFieldSpecified;
    
    private uint paginaPublicacaoField;
    
    private bool paginaPublicacaoFieldSpecified;
    
    private uint numeroDOUField;
    
    private bool numeroDOUFieldSpecified;
    
    private TInformacoesTramitacaoEMEC informacoesTramitacaoEMECField;
    
    /// <remarks/>
    public TTipoAtoComAtoProprio Tipo {
        get {
            return this.tipoField;
        }
        set {
            this.tipoField = value;
        }
    }
    
    /// <remarks/>
    public string Numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public string VeiculoPublicacao {
        get {
            return this.veiculoPublicacaoField;
        }
        set {
            this.veiculoPublicacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataPublicacao {
        get {
            return this.dataPublicacaoField;
        }
        set {
            this.dataPublicacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataPublicacaoSpecified {
        get {
            return this.dataPublicacaoFieldSpecified;
        }
        set {
            this.dataPublicacaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public uint SecaoPublicacao {
        get {
            return this.secaoPublicacaoField;
        }
        set {
            this.secaoPublicacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SecaoPublicacaoSpecified {
        get {
            return this.secaoPublicacaoFieldSpecified;
        }
        set {
            this.secaoPublicacaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public uint PaginaPublicacao {
        get {
            return this.paginaPublicacaoField;
        }
        set {
            this.paginaPublicacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PaginaPublicacaoSpecified {
        get {
            return this.paginaPublicacaoFieldSpecified;
        }
        set {
            this.paginaPublicacaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public uint NumeroDOU {
        get {
            return this.numeroDOUField;
        }
        set {
            this.numeroDOUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumeroDOUSpecified {
        get {
            return this.numeroDOUFieldSpecified;
        }
        set {
            this.numeroDOUFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TInformacoesTramitacaoEMEC InformacoesTramitacaoEMEC {
        get {
            return this.informacoesTramitacaoEMECField;
        }
        set {
            this.informacoesTramitacaoEMECField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public enum TTipoAtoComAtoProprio {
    
    /// <remarks/>
    Parecer,
    
    /// <remarks/>
    Resolução,
    
    /// <remarks/>
    Decreto,
    
    /// <remarks/>
    Portaria,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Lei Federal")]
    LeiFederal,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Lei Estadual")]
    LeiEstadual,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Lei Municipal")]
    LeiMunicipal,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Ato Próprio")]
    AtoPróprio,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosIesEmissora {
    
    private string nomeField;
    
    private uint codigoMECField;
    
    private string cNPJField;
    
    private TEndereco enderecoField;
    
    private TAtoRegulatorioComOuSemEMEC credenciamentoField;
    
    private TAtoRegulatorioComOuSemEMEC recredenciamentoField;
    
    private TAtoRegulatorioComOuSemEMEC renovacaoDeRecredenciamentoField;
    
    private TDadosIesEmissoraMantenedora mantenedoraField;
    
    /// <remarks/>
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    public uint CodigoMEC {
        get {
            return this.codigoMECField;
        }
        set {
            this.codigoMECField = value;
        }
    }
    
    /// <remarks/>
    public string CNPJ {
        get {
            return this.cNPJField;
        }
        set {
            this.cNPJField = value;
        }
    }
    
    /// <remarks/>
    public TEndereco Endereco {
        get {
            return this.enderecoField;
        }
        set {
            this.enderecoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC Credenciamento {
        get {
            return this.credenciamentoField;
        }
        set {
            this.credenciamentoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC Recredenciamento {
        get {
            return this.recredenciamentoField;
        }
        set {
            this.recredenciamentoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC RenovacaoDeRecredenciamento {
        get {
            return this.renovacaoDeRecredenciamentoField;
        }
        set {
            this.renovacaoDeRecredenciamentoField = value;
        }
    }
    
    /// <remarks/>
    public TDadosIesEmissoraMantenedora Mantenedora {
        get {
            return this.mantenedoraField;
        }
        set {
            this.mantenedoraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosIesEmissoraMantenedora {
    
    private string razaoSocialField;
    
    private string cNPJField;
    
    private TEndereco enderecoField;
    
    /// <remarks/>
    public string RazaoSocial {
        get {
            return this.razaoSocialField;
        }
        set {
            this.razaoSocialField = value;
        }
    }
    
    /// <remarks/>
    public string CNPJ {
        get {
            return this.cNPJField;
        }
        set {
            this.cNPJField = value;
        }
    }
    
    /// <remarks/>
    public TEndereco Endereco {
        get {
            return this.enderecoField;
        }
        set {
            this.enderecoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosDiplomaNSF {
    
    private TDadosDiplomado diplomadoField;
    
    private System.DateTime dataConclusaoField;
    
    private bool dataConclusaoFieldSpecified;
    
    private TDadosCursoNSF dadosCursoField;
    
    private TDadosIesEmissora iesEmissoraField;
    
    private SignatureType[] signatureField;
    
    private string idField;
    
    /// <remarks/>
    public TDadosDiplomado Diplomado {
        get {
            return this.diplomadoField;
        }
        set {
            this.diplomadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataConclusao {
        get {
            return this.dataConclusaoField;
        }
        set {
            this.dataConclusaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataConclusaoSpecified {
        get {
            return this.dataConclusaoFieldSpecified;
        }
        set {
            this.dataConclusaoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TDadosCursoNSF DadosCurso {
        get {
            return this.dadosCursoField;
        }
        set {
            this.dadosCursoField = value;
        }
    }
    
    /// <remarks/>
    public TDadosIesEmissora IesEmissora {
        get {
            return this.iesEmissoraField;
        }
        set {
            this.iesEmissoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType[] Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosCursoNSF {
    
    private string nomeCursoField;
    
    private object itemField;
    
    private string nomeHabilitacaoField;
    
    private TModalidadeCurso modalidadeField;
    
    private TTituloConferido tituloConferidoField;
    
    private TGrauConferido grauConferidoField;
    
    private TEndereco enderecoCursoField;
    
    private TPolo poloField;
    
    private TAtoRegulatorioComOuSemEMEC autorizacaoField;
    
    private TAtoRegulatorioComOuSemEMEC reconhecimentoField;
    
    private TAtoRegulatorioComOuSemEMEC renovacaoReconhecimentoField;
    
    /// <remarks/>
    public string NomeCurso {
        get {
            return this.nomeCursoField;
        }
        set {
            this.nomeCursoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CodigoCursoEMEC", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("SemCodigoCursoEMEC", typeof(TInformacoesTramitacaoEMEC))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public string NomeHabilitacao {
        get {
            return this.nomeHabilitacaoField;
        }
        set {
            this.nomeHabilitacaoField = value;
        }
    }
    
    /// <remarks/>
    public TModalidadeCurso Modalidade {
        get {
            return this.modalidadeField;
        }
        set {
            this.modalidadeField = value;
        }
    }
    
    /// <remarks/>
    public TTituloConferido TituloConferido {
        get {
            return this.tituloConferidoField;
        }
        set {
            this.tituloConferidoField = value;
        }
    }
    
    /// <remarks/>
    public TGrauConferido GrauConferido {
        get {
            return this.grauConferidoField;
        }
        set {
            this.grauConferidoField = value;
        }
    }
    
    /// <remarks/>
    public TEndereco EnderecoCurso {
        get {
            return this.enderecoCursoField;
        }
        set {
            this.enderecoCursoField = value;
        }
    }
    
    /// <remarks/>
    public TPolo Polo {
        get {
            return this.poloField;
        }
        set {
            this.poloField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC Autorizacao {
        get {
            return this.autorizacaoField;
        }
        set {
            this.autorizacaoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC Reconhecimento {
        get {
            return this.reconhecimentoField;
        }
        set {
            this.reconhecimentoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC RenovacaoReconhecimento {
        get {
            return this.renovacaoReconhecimentoField;
        }
        set {
            this.renovacaoReconhecimentoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosRegistro {
    
    private TDadosIesRegistradora iesRegistradoraField;
    
    private TLivroRegistro livroRegistroField;
    
    private string idDocumentacaoAcademicaField;
    
    private TSeguranca segurancaField;
    
    private SignatureType[] signatureField;
    
    private string idField;
    
    /// <remarks/>
    public TDadosIesRegistradora IesRegistradora {
        get {
            return this.iesRegistradoraField;
        }
        set {
            this.iesRegistradoraField = value;
        }
    }
    
    /// <remarks/>
    public TLivroRegistro LivroRegistro {
        get {
            return this.livroRegistroField;
        }
        set {
            this.livroRegistroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
    public string IdDocumentacaoAcademica {
        get {
            return this.idDocumentacaoAcademicaField;
        }
        set {
            this.idDocumentacaoAcademicaField = value;
        }
    }
    
    /// <remarks/>
    public TSeguranca Seguranca {
        get {
            return this.segurancaField;
        }
        set {
            this.segurancaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType[] Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosIesRegistradora {
    
    private string nomeField;
    
    private uint codigoMECField;
    
    private string cNPJField;
    
    private TEndereco enderecoField;
    
    private TAtoRegulatorioComOuSemEMEC credenciamentoField;
    
    private TAtoRegulatorioComOuSemEMEC recredenciamentoField;
    
    private TAtoRegulatorioComOuSemEMEC renovacaoDeRecredenciamentoField;
    
    private TDadosIesRegistradoraMantenedora mantenedoraField;
    
    /// <remarks/>
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    public uint CodigoMEC {
        get {
            return this.codigoMECField;
        }
        set {
            this.codigoMECField = value;
        }
    }
    
    /// <remarks/>
    public string CNPJ {
        get {
            return this.cNPJField;
        }
        set {
            this.cNPJField = value;
        }
    }
    
    /// <remarks/>
    public TEndereco Endereco {
        get {
            return this.enderecoField;
        }
        set {
            this.enderecoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC Credenciamento {
        get {
            return this.credenciamentoField;
        }
        set {
            this.credenciamentoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC Recredenciamento {
        get {
            return this.recredenciamentoField;
        }
        set {
            this.recredenciamentoField = value;
        }
    }
    
    /// <remarks/>
    public TAtoRegulatorioComOuSemEMEC RenovacaoDeRecredenciamento {
        get {
            return this.renovacaoDeRecredenciamentoField;
        }
        set {
            this.renovacaoDeRecredenciamentoField = value;
        }
    }
    
    /// <remarks/>
    public TDadosIesRegistradoraMantenedora Mantenedora {
        get {
            return this.mantenedoraField;
        }
        set {
            this.mantenedoraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosIesRegistradoraMantenedora {
    
    private string razaoSocialField;
    
    private string cNPJField;
    
    private TEndereco enderecoField;
    
    /// <remarks/>
    public string RazaoSocial {
        get {
            return this.razaoSocialField;
        }
        set {
            this.razaoSocialField = value;
        }
    }
    
    /// <remarks/>
    public string CNPJ {
        get {
            return this.cNPJField;
        }
        set {
            this.cNPJField = value;
        }
    }
    
    /// <remarks/>
    public TEndereco Endereco {
        get {
            return this.enderecoField;
        }
        set {
            this.enderecoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TLivroRegistro {
    
    private string livroRegistroField;
    
    private string[] itemsField;
    
    private ItemsChoiceType4[] itemsElementNameField;
    
    private string processoDoDiplomaField;
    
    private System.DateTime dataColacaoGrauField;
    
    private System.DateTime dataExpedicaoDiplomaField;
    
    private System.DateTime dataRegistroDiplomaField;
    
    private TLivroRegistroResponsavelRegistro responsavelRegistroField;
    
    /// <remarks/>
    public string LivroRegistro {
        get {
            return this.livroRegistroField;
        }
        set {
            this.livroRegistroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NumeroFolhaDoDiploma", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NumeroRegistro", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NumeroSequenciaDoDiploma", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType4[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    public string ProcessoDoDiploma {
        get {
            return this.processoDoDiplomaField;
        }
        set {
            this.processoDoDiplomaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataColacaoGrau {
        get {
            return this.dataColacaoGrauField;
        }
        set {
            this.dataColacaoGrauField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataExpedicaoDiploma {
        get {
            return this.dataExpedicaoDiplomaField;
        }
        set {
            this.dataExpedicaoDiplomaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataRegistroDiploma {
        get {
            return this.dataRegistroDiplomaField;
        }
        set {
            this.dataRegistroDiplomaField = value;
        }
    }
    
    /// <remarks/>
    public TLivroRegistroResponsavelRegistro ResponsavelRegistro {
        get {
            return this.responsavelRegistroField;
        }
        set {
            this.responsavelRegistroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", IncludeInSchema=false)]
public enum ItemsChoiceType4 {
    
    /// <remarks/>
    NumeroFolhaDoDiploma,
    
    /// <remarks/>
    NumeroRegistro,
    
    /// <remarks/>
    NumeroSequenciaDoDiploma,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TLivroRegistroResponsavelRegistro {
    
    private string nomeField;
    
    private string cPFField;
    
    private string iDouNumeroMatriculaField;
    
    /// <remarks/>
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    public string CPF {
        get {
            return this.cPFField;
        }
        set {
            this.cPFField = value;
        }
    }
    
    /// <remarks/>
    public string IDouNumeroMatricula {
        get {
            return this.iDouNumeroMatriculaField;
        }
        set {
            this.iDouNumeroMatriculaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TSeguranca {
    
    private string codigoValidacaoField;
    
    /// <remarks/>
    public string CodigoValidacao {
        get {
            return this.codigoValidacaoField;
        }
        set {
            this.codigoValidacaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TDadosRegistroNSF {
    
    private TDadosIesRegistradora iesRegistradoraField;
    
    private TLivroRegistroNSF livroRegistroField;
    
    private string idDocumentacaoAcademicaField;
    
    private TSeguranca segurancaField;
    
    private SignatureType[] signatureField;
    
    private string idField;
    
    /// <remarks/>
    public TDadosIesRegistradora IesRegistradora {
        get {
            return this.iesRegistradoraField;
        }
        set {
            this.iesRegistradoraField = value;
        }
    }
    
    /// <remarks/>
    public TLivroRegistroNSF LivroRegistro {
        get {
            return this.livroRegistroField;
        }
        set {
            this.livroRegistroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
    public string IdDocumentacaoAcademica {
        get {
            return this.idDocumentacaoAcademicaField;
        }
        set {
            this.idDocumentacaoAcademicaField = value;
        }
    }
    
    /// <remarks/>
    public TSeguranca Seguranca {
        get {
            return this.segurancaField;
        }
        set {
            this.segurancaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType[] Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TLivroRegistroNSF {
    
    private string livroRegistroField;
    
    private string[] itemsField;
    
    private ItemsChoiceType5[] itemsElementNameField;
    
    private string processoDoDiplomaField;
    
    private System.DateTime dataColacaoGrauField;
    
    private System.DateTime dataExpedicaoDiplomaField;
    
    private System.DateTime dataRegistroDiplomaField;
    
    private TLivroRegistroNSFResponsavelRegistro responsavelRegistroField;
    
    /// <remarks/>
    public string LivroRegistro {
        get {
            return this.livroRegistroField;
        }
        set {
            this.livroRegistroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NumeroFolhaDoDiploma", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NumeroRegistro", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NumeroSequenciaDoDiploma", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType5[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    public string ProcessoDoDiploma {
        get {
            return this.processoDoDiplomaField;
        }
        set {
            this.processoDoDiplomaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataColacaoGrau {
        get {
            return this.dataColacaoGrauField;
        }
        set {
            this.dataColacaoGrauField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataExpedicaoDiploma {
        get {
            return this.dataExpedicaoDiplomaField;
        }
        set {
            this.dataExpedicaoDiplomaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataRegistroDiploma {
        get {
            return this.dataRegistroDiplomaField;
        }
        set {
            this.dataRegistroDiplomaField = value;
        }
    }
    
    /// <remarks/>
    public TLivroRegistroNSFResponsavelRegistro ResponsavelRegistro {
        get {
            return this.responsavelRegistroField;
        }
        set {
            this.responsavelRegistroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", IncludeInSchema=false)]
public enum ItemsChoiceType5 {
    
    /// <remarks/>
    NumeroFolhaDoDiploma,
    
    /// <remarks/>
    NumeroRegistro,
    
    /// <remarks/>
    NumeroSequenciaDoDiploma,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public partial class TLivroRegistroNSFResponsavelRegistro {
    
    private string nomeField;
    
    private string cPFField;
    
    private string iDouNumeroMatriculaField;
    
    /// <remarks/>
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    public string CPF {
        get {
            return this.cPFField;
        }
        set {
            this.cPFField = value;
        }
    }
    
    /// <remarks/>
    public string IDouNumeroMatricula {
        get {
            return this.iDouNumeroMatriculaField;
        }
        set {
            this.iDouNumeroMatriculaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
public enum TVersao {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.02")]
    Item102,
}
